FROM java:8
ADD target/model.EmployeeManagementSystemModel-0.0.1-SNAPSHOT.jar model.EmployeeManagementSystemModel-0.0.1-SNAPSHOT.jar
EXPOSE 8082
ENTRYPOINT ["java", "-jar", "model.EmployeeManagementSystemModel-0.0.1-SNAPSHOT.jar"]