FROM java:8
ADD target/EmployeeManagementSystemUI-0.0.1-SNAPSHOT.jar EmployeeManagementSystemUI-0.0.1-SNAPSHOT.jar
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "EmployeeManagementSystemUI-0.0.1-SNAPSHOT.jar"]