FROM java:8
ADD target/EmployeeManagementSystemOauthServer-0.0.1-SNAPSHOT.jar EmployeeManagementSystemOauthServer-0.0.1-SNAPSHOT.jar
EXPOSE 9191
ENTRYPOINT ["java", "-jar", "EmployeeManagementSystemOauthServer-0.0.1-SNAPSHOT.jar"]